### ISSUE TITLE
Does not boot when GPIO15 is soldered to the mainboard

### ISSUE THREAD

**Issue by aik** [kireque/esphome_nebula_light#5]
If I leave it hanging and have 10kOhm resistor - things work. I'm confused but not much - I do not want the button and led anyway :)

**Comment by ashinckley** [comment]
I recently tried this mod, and I cannot get the ESP to boot.  I'm a little confused on what you mean by leaving it hanging.  Were you able to prevent GPIO15 from contacting the main board of the PCB?

**Comment by aik** [comment]
ESP would not boot if the pin was soldered to the main board. Still needed the pulldown (?) resistor. I programmed the ESP on a dev board, made sure it boots, and started soldering pins one by one and checking if it is booting or not. GPIO15 was the one to break booting, dunno why.

**Comment by kireque** [comment]
You still need the pull down resistor when it's soldered to the PCB as stated in the readme.
I have soldered all of the pins and did not encounter any issues during the boot process of the esp.
