### ISSUE TITLE
What would be the replacement for CBU chip?

### ISSUE THREAD

**Issue by soubhik-khan** [kireque/esphome_nebula_light#6]
My projector came with a CBU chip wich has 7 pins all 3 sides. Is there any ESP chip that I can replace with? Or do I need to solder wires instead of soldering the chip to the PCB? 
Found the CBU datasheet  - https://developer.tuya.com/en/docs/iot/cbu-module-datasheet?id=Ka07pykl5dk4u
I hope this can be replaced with some ESP chip!
![PXL_20230627_053924102](https://github.com/kireque/esphome_nebula_light/assets/16430033/87d7fd01-9d1d-4b68-9c02-16115dbef715)

**Comment by fonix232** [comment]
You don't need to replace the chip - you can use [tuya-cloudcutter](https://github.com/tuya-cloudcutter/tuya-cloudcutter) to flash ESPHome on the BK7231T (for the original model using the Tuya WB3S module), or BK7321N (for your unit using the CBU model). Then just line up the pins with the original, and you can more or less use the config as shown in the README.

**Comment by kireque** [comment]
Resolution given
